#!/usr/bin/env node
// Patches pkg/package.json generated by wasm-pack to add missing peerDependencies.
import { readFileSync, writeFileSync } from 'fs'

const pkgPath = new URL('../pkg/package.json', import.meta.url).pathname
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))

pkg.peerDependencies = {
  'web-tree-sitter': '^0.25.0',
}

writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n')
console.log('Patched pkg/package.json with peerDependencies.')
