#!/usr/bin/env node
console.error(
  [
    "========================================================================",
    "WARNING: `sg` is deprecated. Use `ast-grep` instead.",
    "========================================================================",
  ].join("\n"),
);
require("./ast-grep");
